import { appShell, esc } from './layout.js';
import { icon } from './icons.js';

const allowedStatuses = new Set(['online', 'idle', 'dnd', 'invisible']);
const activityTypes = new Set(['Playing', 'Listening', 'Watching', 'Competing']);

export function renderMultibotConfig({ user, bot, csrf }) {
  const settings = bot.settings || {};
  const status = allowedStatuses.has(settings.presenceStatus) ? settings.presenceStatus : 'online';
  const activityType = activityTypes.has(settings.activityType) ? settings.activityType : 'Playing';
  const online = bot.status === 'online';
  const avatarUrl = String(settings.avatarUrl || '').trim();
  const bannerUrl = String(settings.bannerUrl || '').trim();
  const body = `<div class="page-head"><div class="eyebrow">Multibot B1 · Configuración</div><h1>${icon('settings', 22)} ${esc(settings.name || bot.bot_username || 'Bot')}</h1><p>Personaliza esta instancia sin afectar a tus otros bots.</p></div>
  <div class="grid" style="max-width:1100px">
    <div class="card"><div class="row spread" style="margin-bottom:18px"><div><h2>${icon('bot', 19)} Perfil del bot</h2><p class="hint" style="margin:5px 0 0">${esc(bot.bot_username || 'Bot')} · ID ${esc(bot.bot_user_id)}</p></div><span class="badge ${online ? 'on' : 'off'}">● ${online ? 'online' : 'offline'}</span></div><div class="grid-2"><div><label class="field">Nombre personalizado</label><input id="bot-name" type="text" maxlength="32" value="${esc(settings.name || '')}" placeholder="Mi Bot"><p class="hint">Se aplicará como nombre de usuario del bot en Discord.</p></div><div><label class="field">Idioma del panel</label><select id="bot-language"><option value="es" ${settings.language !== 'en' ? 'selected' : ''}>Español</option><option value="en" ${settings.language === 'en' ? 'selected' : ''}>English</option></select></div></div><div style="margin-top:16px"><label class="field">Descripción privada</label><textarea id="bot-description" maxlength="500" rows="4" placeholder="Describe para qué usarás este bot…">${esc(settings.description || '')}</textarea><p class="hint">Esta descripción queda guardada en tu configuración de Wolf.</p></div></div>
    <div class="card media-card"><div class="row spread" style="margin-bottom:14px"><div><h2>🖼️ Imagen de perfil</h2><p class="hint" style="margin:5px 0 0">Sube una imagen desde tu PC y ajusta el encuadre antes de aplicarla.</p></div><span class="badge">512 × 512</span></div><div class="media-editor" id="avatar-editor"><div class="media-stage avatar-stage" id="avatar-stage"><div class="checker"></div><canvas id="avatar-canvas" width="512" height="512"></canvas><div class="media-empty" id="avatar-empty" style="display:${avatarUrl ? 'none' : 'flex'}">Sin imagen</div></div><div class="media-controls"><input id="avatar-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden><div class="row" style="flex-wrap:wrap"><button type="button" class="btn" onclick="document.getElementById('avatar-file').click()">📁 Subir imagen</button><button type="button" class="btn btn-ghost" onclick="resetImageEditor('avatar')">↺ Restablecer</button><button type="button" class="btn btn-ghost" onclick="clearImage('avatar')">✕ Quitar</button></div><label class="field" style="margin-top:15px">Zoom <span id="avatar-zoom-label">100%</span></label><input id="avatar-zoom" class="range" type="range" min="100" max="300" step="1" value="100"><div class="grid-2" style="margin-top:10px"><div><label class="field">Horizontal</label><input id="avatar-x" class="range" type="range" min="-100" max="100" value="0"></div><div><label class="field">Vertical</label><input id="avatar-y" class="range" type="range" min="-100" max="100" value="0"></div></div><p class="hint">También puedes arrastrar la imagen directamente dentro del recuadro.</p></div></div><input id="bot-avatar" type="hidden" value="${esc(avatarUrl)}"></div>
    <div class="card media-card"><div class="row spread" style="margin-bottom:14px"><div><h2>🖼️ Banner del bot</h2><p class="hint" style="margin:5px 0 0">Crea el banner directamente desde una imagen de tu PC y controla exactamente qué parte se muestra.</p></div><span class="badge">1200 × 480</span></div><div class="media-editor" id="banner-editor"><div class="media-stage banner-stage" id="banner-stage"><div class="checker"></div><canvas id="banner-canvas" width="1200" height="480"></canvas><div class="media-empty" id="banner-empty" style="display:${bannerUrl ? 'none' : 'flex'}">Sin banner</div></div><div class="media-controls"><input id="banner-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden><div class="row" style="flex-wrap:wrap"><button type="button" class="btn" onclick="document.getElementById('banner-file').click()">📁 Subir imagen</button><button type="button" class="btn btn-ghost" onclick="resetImageEditor('banner')">↺ Restablecer</button><button type="button" class="btn btn-ghost" onclick="clearImage('banner')">✕ Quitar</button></div><label class="field" style="margin-top:15px">Zoom <span id="banner-zoom-label">100%</span></label><input id="banner-zoom" class="range" type="range" min="100" max="300" step="1" value="100"><div class="grid-2" style="margin-top:10px"><div><label class="field">Horizontal</label><input id="banner-x" class="range" type="range" min="-100" max="100" value="0"></div><div><label class="field">Vertical</label><input id="banner-y" class="range" type="range" min="-100" max="100" value="0"></div></div><p class="hint">El resultado se redimensiona y comprime automáticamente para mantener el panel ligero.</p><p id="banner-error" class="hint media-error" style="display:none">No se pudo cargar este banner. Usa «Subir imagen» para reemplazarlo.</p></div></div><input id="bot-banner" type="hidden" value="${esc(bannerUrl)}"></div>
    <div class="card"><h2>${icon('wave', 19)} Presencia de Discord</h2><p class="hint">Controla el estado y la actividad que verán los usuarios.</p><div class="grid-2" style="margin-top:16px"><div><label class="field">Estado</label><select id="presence-status"><option value="online" ${status === 'online' ? 'selected' : ''}>🟢 Online</option><option value="idle" ${status === 'idle' ? 'selected' : ''}>🌙 Ausente</option><option value="dnd" ${status === 'dnd' ? 'selected' : ''}>⛔ No molestar</option><option value="invisible" ${status === 'invisible' ? 'selected' : ''}>⚫ Invisible</option></select></div><div><label class="field">Tipo de actividad</label><select id="activity-type"><option value="Playing" ${activityType === 'Playing' ? 'selected' : ''}>Jugando</option><option value="Listening" ${activityType === 'Listening' ? 'selected' : ''}>Escuchando</option><option value="Watching" ${activityType === 'Watching' ? 'selected' : ''}>Viendo</option><option value="Competing" ${activityType === 'Competing' ? 'selected' : ''}>Compitiendo</option></select></div></div><div style="margin-top:16px"><label class="field">Texto de actividad</label><input id="activity-text" type="text" maxlength="128" value="${esc(settings.activityText || '')}" placeholder="mi servidor"></div></div>
    <div class="card"><h2>${icon('shield', 19)} Estado de la instancia</h2><p class="hint">Puedes encender o apagar esta instancia sin tocar las demás.</p><div class="row" style="flex-wrap:wrap;margin-top:16px">${online ? `<button type="button" class="btn-ghost" onclick="stopBot()">⏹ Apagar</button>` : `<button type="button" onclick="startBot()">▶ Encender</button>`}<button type="button" onclick="saveBot()">${icon('check', 15)} Guardar cambios</button><a class="btn btn-ghost" href="/bots">← Volver a mis bots</a></div><p id="msg" class="hint" style="min-height:20px;margin:12px 0 0"></p></div>
  </div>
  <style>.media-card{min-width:0;overflow:hidden}.media-editor{display:grid;grid-template-columns:minmax(0,1fr);gap:18px;align-items:start}.media-stage{position:relative;width:100%;max-width:100%;overflow:hidden;border:1px solid rgba(255,255,255,.09);border-radius:16px;background:rgba(255,255,255,.035);touch-action:none;user-select:none}.avatar-stage{aspect-ratio:1/1;margin:auto}.banner-stage{aspect-ratio:2.5/1}.media-stage canvas{position:absolute;inset:0;width:100%;height:100%;display:block;cursor:grab}.media-stage.dragging canvas{cursor:grabbing}.checker{position:absolute;inset:0}.media-empty{position:absolute;inset:0;align-items:center;justify-content:center;color:rgba(255,255,255,.42);font-size:14px;pointer-events:none}.media-controls{min-width:0;width:100%;overflow:hidden}.range{width:100%;max-width:100%}.media-error{margin-top:8px}@media(max-width:800px){.avatar-stage{max-width:100%}}</style>
  <script>
    const CSRF = ${JSON.stringify(csrf)}; const BOT_ID = ${JSON.stringify(String(bot.id))};
    const initialImages={avatar:${JSON.stringify(avatarUrl)},banner:${JSON.stringify(bannerUrl)}};
    const editors={avatar:{width:512,height:512,image:null,zoom:100,x:0,y:0,source:initialImages.avatar,dirty:false},banner:{width:1200,height:480,image:null,zoom:100,x:0,y:0,source:initialImages.banner,dirty:false}};
    async function api(url,method,body){const r=await fetch(url,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':CSRF},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||data.error||'request_failed');return data;}
    function fitCover(img,w,h,z,x,y){const base=Math.max(w/img.naturalWidth,h/img.naturalHeight),scale=base*(z/100),dw=img.naturalWidth*scale,dh=img.naturalHeight*scale,maxX=Math.max(0,(dw-w)/2),maxY=Math.max(0,(dh-h)/2);return{dw,dh,dx:(w-dw)/2+maxX*(x/100),dy:(h-dh)/2+maxY*(y/100)}}
    function drawEditor(k){const s=editors[k],c=document.getElementById(k+'-canvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,s.width,s.height);if(!s.image)return;const p=fitCover(s.image,s.width,s.height,s.zoom,s.x,s.y);ctx.drawImage(s.image,p.dx,p.dy,p.dw,p.dh);document.getElementById(k+'-zoom-label').textContent=s.zoom+'%';document.getElementById(k+'-zoom').value=s.zoom;document.getElementById(k+'-x').value=s.x;document.getElementById(k+'-y').value=s.y;}
    function loadImage(k,source){const s=editors[k],empty=document.getElementById(k+'-empty'),err=document.getElementById(k+'-error');if(!source){s.image=null;empty.style.display='flex';if(err)err.style.display='none';drawEditor(k);return}const img=new Image();if(/^https?:\\/\\//i.test(source))img.crossOrigin='anonymous';img.onload=()=>{s.image=img;empty.style.display='none';if(err)err.style.display='none';drawEditor(k)};img.onerror=()=>{s.image=null;empty.style.display='flex';if(err)err.style.display='block'};img.src=source}
    function resetImageEditor(k){const s=editors[k];s.zoom=100;s.x=0;s.y=0;s.source=initialImages[k];s.dirty=false;document.getElementById(k==='avatar'?'bot-avatar':'bot-banner').value=s.source;loadImage(k,s.source)}
    function clearImage(k){const s=editors[k];s.image=null;s.source='';s.dirty=true;s.zoom=100;s.x=0;s.y=0;document.getElementById(k==='avatar'?'bot-avatar':'bot-banner').value='';document.getElementById(k+'-empty').style.display='flex';drawEditor(k)}
    function setMessage(t){document.getElementById('msg').textContent=t}
    function bindRange(k,f){document.getElementById(k+'-'+f).addEventListener('input',e=>{editors[k][f]=Number(e.target.value);editors[k].dirty=true;drawEditor(k)})}
    function bindFile(k){document.getElementById(k+'-file').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>12*1024*1024){setMessage('La imagen es demasiado grande. Máximo 12 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{editors[k].source=reader.result;editors[k].zoom=100;editors[k].x=0;editors[k].y=0;editors[k].dirty=true;document.getElementById(k==='avatar'?'bot-avatar':'bot-banner').value='';loadImage(k,reader.result)};reader.readAsDataURL(file);e.target.value=''})}
    function bindDrag(k){const stage=document.getElementById(k+'-stage');let start=null;stage.addEventListener('pointerdown',e=>{if(!editors[k].image)return;stage.setPointerCapture(e.pointerId);start={px:e.clientX,py:e.clientY,x:editors[k].x,y:editors[k].y};stage.classList.add('dragging')});stage.addEventListener('pointermove',e=>{if(!start)return;const r=stage.getBoundingClientRect(),s=editors[k];s.x=Math.max(-100,Math.min(100,start.x+(e.clientX-start.px)*200/Math.max(1,r.width)));s.y=Math.max(-100,Math.min(100,start.y+(e.clientY-start.py)*200/Math.max(1,r.height)));s.dirty=true;drawEditor(k)});const end=()=>{start=null;stage.classList.remove('dragging')};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end)}
    function canvasToDataUrl(k){const s=editors[k];if(!s.image)return'';const c=document.getElementById(k+'-canvas');let q=.82,data=c.toDataURL('image/jpeg',q);while(data.length>280000&&q>.45){q-=.07;data=c.toDataURL('image/jpeg',q)}return data}
    function collectSettings(){const a=editors.avatar,b=editors.banner;return{name:document.getElementById('bot-name').value.trim(),language:document.getElementById('bot-language').value,description:document.getElementById('bot-description').value.trim(),avatarUrl:a.dirty?canvasToDataUrl('avatar'):document.getElementById('bot-avatar').value.trim(),bannerUrl:b.dirty?canvasToDataUrl('banner'):document.getElementById('bot-banner').value.trim(),presenceStatus:document.getElementById('presence-status').value,activityType:document.getElementById('activity-type').value,activityText:document.getElementById('activity-text').value.trim()}}
    let saving=false;
    async function saveBot(){if(saving)return;saving=true;const msg=document.getElementById('msg'),button=document.querySelector('button[onclick="saveBot()"]');if(button)button.disabled=true;setMessage('Guardando cambios…');try{const settings=collectSettings();if(JSON.stringify(settings).length>900000)throw new Error('Las imágenes siguen siendo demasiado grandes.');await api('/api/multibot/'+BOT_ID,'PATCH',{settings});editors.avatar.dirty=false;editors.banner.dirty=false;if(settings.avatarUrl)document.getElementById('bot-avatar').value=settings.avatarUrl;if(settings.bannerUrl)document.getElementById('bot-banner').value=settings.bannerUrl;setMessage('✓ Cambios guardados y aplicados.');}catch(e){setMessage('❌ No se pudo guardar: '+e.message)}finally{saving=false;if(button)button.disabled=false}}
    async function startBot(){setMessage('Conectando con Discord…');try{await api('/api/multibot/'+BOT_ID+'/start','POST');setMessage('✓ Bot encendido.');setTimeout(()=>location.reload(),500)}catch(e){setMessage('❌ No se pudo encender: '+e.message)}}
    async function stopBot(){setMessage('Desconectando…');try{await api('/api/multibot/'+BOT_ID+'/stop','POST');setMessage('✓ Bot apagado.');setTimeout(()=>location.reload(),500)}catch(e){setMessage('❌ No se pudo apagar: '+e.message)}}
    ['zoom','x','y'].forEach(f=>{bindRange('avatar',f);bindRange('banner',f)});['avatar','banner'].forEach(k=>{bindFile(k);bindDrag(k);loadImage(k,editors[k].source)});
  </script>`;
  return appShell({title:`Configurar ${settings.name||bot.bot_username||'Bot'}`,user,active:'multibot',body});
}